---
title: "DQL"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(shiny)
library(nortest)
library(car)
library(ExpDes.pt)
library(rmarkdown)
library(plotly)

dataset=whichdataset()
    respo<-dataset[input$resp]
    respos <- unlist(respo)
    trata<-dataset[input$trat]
    trat <- unlist(trata)
    lin<-dataset[input$linha]
    linh <- unlist(lin)
    col<-dataset[input$coluna]
    colu <- unlist(col)
    
    sigT2 <- as.numeric(input$sigT2)
    sigF2 <- as.numeric(input$sigF2)
    
     if(input$quali==TRUE)
      trat = as.factor(trat)
    if(input$quali==FALSE)
      trat = as.numeric(trat)
    
dql.model=dql(trat, linh, colu, respos, quali=input$quali, mcomp=input$mcomp2, sigT=sigT2, sigF=sigF2)
    
```    
 
 

```{r echo=TRUE}
#######################################################
#                    Dados                            # 
#######################################################

dataset


#######################################################
#              Estrutura dos dados                    # 
#######################################################

 summary(dataset)
 str(dataset)
 

#######################################################
#               Tabela ANOVA DQL                      #  #######################################################

dql(trat, linh, colu, respos, quali=input$quali, mcomp=input$mcomp2, sigT=sigT2, sigF=sigF2)


#######################################################
#           Plot Residuos                             # 
#######################################################

plotres(dql.model)
