---
title: "FATORIAL TRIPLO COM UM TRATAMENTO ADICIONAL EM DIC"
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(shiny)
library(nortest)
library(car)
library(ExpDes.pt)
library(rmarkdown)

dataset=whichdataset()
    respo<-dataset[input$resp]
    respos <- unlist(respo)
    repe<-dataset[input$repeticao]
    repet <- unlist(repe)
    fat<-dataset[input$fator1]
    fat1 <- unlist(fat)
    fato<-dataset[input$fator2]
    fat2 <- unlist(fato)
    fatoo<-dataset[input$fator3]
    fat3 <- unlist(fatoo)
    respadi<-dataset[input$respad]
    respAd <- unlist(respadi)
    
    sigT9 <- as.numeric(input$sigT9)
    sigF9 <- as.numeric(input$sigF9)
    
fat3.ad.dic.model<-fat3.ad.dic(fat1, fat2, fat3, repet, respos, respAd, quali = c(input$quali1, input$quali2, input$quali3), mcomp=input$mcomp9, sigT=sigT9, sigF=sigF9)    
```


```{r echo=TRUE}
#######################################################
#                    Dados                            # 
#######################################################
dataset


#######################################################
#              Estrutura dos dados                    # 
#######################################################
 summary(dataset)
 str(dataset)
 
 
#################################################################
#Tabela ANOVA FATORIAL TRIPLO COM UM TRATAMENTO ADICIONAL EM DIC#  #################################################################
    
fat3.ad.dic(fat1, fat2, fat3, repet, respos, respAd, quali = c(input$quali1, input$quali2, input$quali3), mcomp=input$mcomp9, sigT=sigT9, sigF=sigF9)

#######################################################
#           Análise de resíduo                        # 
#######################################################

plotres(fat3.ad.dic.model)

```
