---
title: "PARCELAS SUBDIVIDIDAS EM DBC"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(shiny)
library(nortest)
library(car)
library(ExpDes.pt)
library(rmarkdown)

dataset=whichdataset()
    respo<-dataset[input$resp]
    respos <- unlist(respo)
    bloco<-dataset[input$bloc]
    blocos <- unlist(bloco)
    fat<-dataset[input$fator1]
    fat1 <- unlist(fat)
    fato<-dataset[input$fator2]
    fat2 <- unlist(fato)
    
    sigT12 <- as.numeric(input$sigT12)
    sigF12 <- as.numeric(input$sigF12)
    
   psub2.dbc.model<-psub2.dbc(fat1, fat2, blocos, respos, quali = c(input$quali1, input$quali2), mcomp=input$mcomp12, sigT=sigT12, sigF=sigF12)
```


```{r echo=TRUE}
#######################################################
#                    Dados                            # 
#######################################################
dataset

#######################################################
#              Estrutura dos dados                    # 
#######################################################

 summary(dataset)
 str(dataset)
 

#################################################################
#           Tabela ANOVA PARCELAS SUBDIVIDIDAS EM DBC           #  #################################################################
psub2.dbc(fat1, fat2, blocos, respos, quali = c(input$quali1, input$quali2), mcomp=input$mcomp12, sigT=sigT12, sigF=sigF12)

#######################################################
#        Análise de resíduo                           # 
#######################################################

plotres(psub2.dbc.model)

```
